---
- hosts: aws
  gather_facts: yes
  become: true

  tasks:
    - name: Install nginx
      apt: pkg=nginx state=present
    - name: Install software-properties-common
      apt: pkg=software-properties-common state=present
    - name: add nodejs apt key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: install nodejs
      apt_repository:
        repo: deb https://deb.nodesource.com/node_13.x bionic main
        update_cache: yes
    - name: install nodejs
      apt:
        update_cache: yes
        name: nodejs
        state: present
    - name: start npm
      shell: |
        cd app/app/
        npm install
        npm start
