---
- hosts: web
  gather_facts: yes
  become: true
  tasks:
    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: Installing nodejs
      apt_repository:
        repo: deb https://deb.nodesource.com/node_13.x bionic main
        update_cache: yes
    - name: "Install nodejs"
      apt:
        update_cache: yes
        name: nodejs
        state: present
